export const LANG = {
    en: {
        topheader_mail_text: "Myfest.co.in",
        topheader_phone: "Phone",
        topheader_phone_text: "9324505363",
        topheader_language: "Language",
        language_english: "English",
        language_marathi: "Marathi",
        navbar_brand: "Brand",
        nav_silver_plan: "Silver Plan",
        nav_gold_plan: "Gold Plan",
        hero_section_p1: "A vibrant festival that brings families and communities together to welcome wisdom, prosperity, and new beginnings.",
        hero_section_btn1: "Download MyFest Now",
        section2_h2_1: "MyFest – Digital Management of Your Ganesh Festival Now Accessible!",
        section2_p1: "With the help of 'MyFest' app, digital management of Ganesh festival has become even easier and more convenient! Through the digital report feature, you can see previous financial transactions and accounts in one click. Understand the importance of Ganesh festival and other festivals through Festival Books. Use a digital receipt system for donation management and keep all donor information secure.",
        section2_p2: "Watch live Ganpati darshan from around the world and see your beloved deity. Through the digital advertisement monthly, publicize the mandal's initiatives. Preserve and share all festival memories in the photo gallery. Manage with fewer documents, paperless management, and operate the app easily using a simple operation system. Download 'MyFest' and make Ganesh festival digital!",
        section3_h2_1: "Vakratund Mahakay Suryakoti Samprabh. Nirvighn Kuru Me Dev Sarvakaryeshu Sarvada.",
        section4_h2_1: "Key Features MyFest",
        section4_box1_h3: "Digital Receipt",
        section4_box1_p: "Donation management now fully digital! Issue receipts to donors in one click and keep accounts.",
        section4_box2_h3: "Photo Gallery",
        section4_box2_p: "All beautiful moments of Ganesh festival in one place! Save and share photos and memories.",
        section4_box3_h3: "Digital Report",
        section4_box3_p: "Get complete financial report of your Ganpati mandal in one click! Check previous account details and maintain transparent management.",
        section4_box4_h3: "Digital Ad Magazine",
        section4_box4_p: "Digital advertising facility for various mandal initiatives. Excellent advertising opportunities available for sponsors.",
        section4_box5_h3: "Live Ganpati Darshan",
        section4_box5_p: "Get complete financial report of your Ganpati mandal in one click! Check previous account details and maintain transparent management.",
        section4_box6_h3: "Digital Arati Book",
        section4_box6_p: "Manage daily arati of your Ganpati mandal completely in just one click! Easily check past arati records and maintain transparent and organized management.",
        section6_h2_1: "App Plan Details",
        section6_silver_h3: "SILVER PLAN",
        section6_silver_span1: "App cost for lifetime",
        section6_silver_span2: "₹ 5100",
        section6_silver_li1: "Digital Receipt",
        section6_silver_li2: "Photo Gallery",
        section6_silver_li3: "Digital Report",
        section6_silver_btn: "Click Here",
        section6_silver_maint: "Annual Maintenance Fee",
        section6_silver_p1: "Silver: ₹1100",
        section6_silver_p2: "No extra charges for these:",
        section6_silver_p3: "1) SMS Messages\n2) Monthly Newsletter",
        section6_gold_h3: "GOLD PLAN",
        section6_gold_span1: "App cost for lifetime",
        section6_gold_span2: "₹11000",
        section6_gold_li1: "Digital Receipt",
        section6_gold_li2: "Photo Gallery",
        section6_gold_li3: "Digital Report",
        section6_gold_li4: "Digital Ad Magazine",
        section6_gold_li5: "Live Ganpati Darshan",
        section6_gold_li6: "Digital Arati Book",
        section6_gold_btn: "Click Here",
        section6_gold_maint: "Annual Maintenance Fee",
        section6_gold_p1: "Gold: ₹1100",
        section6_gold_p2: "No extra charges for these:",
        section6_gold_p3: "1) SMS Messages\n2) Monthly Newsletter",
        footer_title: "Download 'MyFest' and make Ganesh festival digital!",
        footer_description: "Use a digital receipt system for donation management and keep all donor information secure.",
    },
    mr: {
        topheader_mail_text: "Myfest.co.in",
        topheader_phone: "फोन",
        topheader_phone_text: "9324505363",
        topheader_language: "भाषा",
        language_english: "English",
        language_marathi: "मराठी",
        navbar_brand: "ब्रँड",
        nav_silver_plan: "सिल्व्हर प्लान",
        nav_gold_plan: "गोल्ड प्लान",
        hero_section_p1: "एक उत्साही सण जो कुटुंबे आणि समुदायांना एकत्र आणतो, ज्ञान, समृद्धी आणि नवीन सुरुवातीचे स्वागत करण्यासाठी.",
        hero_section_btn1: "माझे फेस्ट आता डाउनलोड करा",
        section2_h2_1: "मायफेस्ट – तुमच्या गणेशोत्सवाचे डिजिटल व्यवस्थापन आता सुलभ!",
        section2_p1: "मायफेस्ट ऍपच्या मदतीने गणेशोत्सवाचे डिजिटल व्यवस्थापन आता अधिक सोपे आणि सुविधाजनक झाले आहे! डिजिटल अहवाल फीचरच्या माध्यमातून पूर्वीचे आर्थिक व्यवहार आणि हिशोब एका क्लिकवर पाहता येतील. गणेशोत्सव आणि इतर सणांचे महत्त्व फेस्टिव्ह बुक्सच्या द्वारे समजून घ्या. देणगी व्यवस्थापनासाठी डिजिटल पावती प्रणाली वापरा आणि संपूर्ण देणगीदार माहिती सुरक्षित ठेवा.",
        section2_p2: "लाईव्ह गणपती दर्शनाने जगभरातून आपल्या बाप्पांचे दर्शन घ्या. डिजिटल जाहिरात मासिकाच्या मदतीने मंडळाचे उपक्रम प्रसिद्ध करा. फोटो गॅलरीमध्ये उत्सवाचे सर्व आठवणींचे जतन करा आणि शेअर करा. कमी कागदपत्रांसह पेपरलेस व्यवस्थापन करा आणि सोपी ऑपरेशन प्रणाली वापरून सहज ऍप ऑपरेट करा. 'मायफेस्ट' डाउनलोड करा आणि गणेशोत्सव डिजिटल बनवा!",
        section3_h2_1: "वक्रतुण्ड महाकाय सूर्यकोटि समप्रभ। निर्विघ्नं कुरु मे देव सर्वकार्येषु सर्वदा॥",
        section4_h2_1: "प्रमुख वैशिष्ट्ये मायफेस्ट",
        section4_box1_h3: "डिजिटल पावती (Digital Receipt)",
        section4_box1_p: "देणगी व्यवस्थापन आता पूर्णतः डिजिटल! एका क्लिकवर देणगीदारांना पावती द्या आणि हिशोब ठेवा.",
        section4_box2_h3: "फोटो गॅलरी (Photo Gallery)",
        section4_box2_p: "गणेशोत्सवाचे सर्व सुंदर क्षण एका जागी! फोटो आणि आठवणी जतन करा आणि शेअर करा.",
        section4_box3_h3: "डिजिटल अहवाल (Digital Ahawal)",
        section4_box3_p: "आता तुमच्या गणपती मंडळाच्या आर्थिक व्यवहारांचा संपूर्ण अहवाल एका क्लिकवर मिळवा! पूर्वीच्या हिशोबांची माहिती तपासा आणि पारदर्शक व्यवस्थापन करा.",
        section4_box4_h3: "डिजिटल जाहिरात मासिक (Digital Ad Magazine)",
        section4_box4_p: "मंडळाच्या विविध उपक्रमांसाठी डिजिटल जाहिरात सुविधा. प्रायोजकांसाठी उत्कृष्ट जाहिरात संधी उपलब्ध.",
        section4_box5_h3: "लाईव्ह गणपती दर्शन (Live Ganpati Darshan)",
        section4_box5_p: "आता तुमच्या गणपती मंडळाच्या आर्थिक व्यवहारांचा संपूर्ण अहवाल एका क्लिकवर मिळवा! पूर्वीच्या हिशोबांची माहिती तपासा आणि पारदर्शक व्यवस्थापन करा.",
        section4_box6_h3: "डिजिटल आरती बुक (Digital Arati Book)",
        section4_box6_p: "आता आपल्या गणपती मंडळाच्या दररोजच्या आरतीचे संपूर्ण व्यवस्थापन फक्त एका क्लिकवर! मागील आरतीचे रेकॉर्ड सहज तपासा आणि पारदर्शक व सुस्थित व्यवस्थापन राखा.",
        section6_h2_1: "ॲप योजना तपशील",
        section6_silver_h3: "SILVER PLAN",
        section6_silver_span1: "आयुष्यभरासाठी ॲप खर्च",
        section6_silver_span2: "₹ 5100",
        section6_silver_li1: "डिजिटल पावती",
        section6_silver_li2: "फोटो गॅलरी",
        section6_silver_li3: "डिजिटल अहवाल",
        section6_silver_btn: "येथे क्लिक करा",
        section6_silver_maint: "वार्षिक देखभाल शुल्क",
        section6_silver_p1: "सिल्व्हर : ₹1100",
        section6_silver_p2: "या गोष्टींसाठी अजिबात अतिरिक्त पैसे नाहीत:",
        section6_silver_p3: "1) एसएमएस संदेश\n2) मासिक बातम्या",
        section6_gold_h3: "GOLD PLAN",
        section6_gold_span1: "आयुष्यभरासाठी ॲप खर्च",
        section6_gold_span2: "₹11000",
        section6_gold_li1: "डिजिटल पावती",
        section6_gold_li2: "फोटो गॅलरी",
        section6_gold_li3: "डिजिटल अहवाल",
        section6_gold_li4: "डिजिटल जाहिरात मासिक",
        section6_gold_li5: "लाईव्ह गणपती दर्शन",
        section6_gold_li6: "डिजिटल आरती पुस्तक",
        section6_gold_btn: "येथे क्लिक करा",
        section6_gold_maint: "वार्षिक देखभाल शुल्क",
        section6_gold_p1: "सिल्व्हर : ₹1100",
        section6_gold_p2: "या गोष्टींसाठी अजिबात अतिरिक्त पैसे नाहीत:",
        section6_gold_p3: "1) एसएमएस संदेश\n2) मासिक बातम्या",
        footer_title: "'मायफेस्ट' डाउनलोड करा आणि गणेशोत्सव डिजिटल बनवा!",
        footer_description: "देणगी व्यवस्थापनासाठी डिजिटल पावती प्रणाली वापरा आणि संपूर्ण देणगीदार माहिती सुरक्षित ठेवा.",
    }
};